"""The ONE definition of how a benchmark program is classified for the paper.

Every script that produces a figure of the paper imports this module instead of
re-implementing the pipeline. Before 2026-09-30 four scripts carried their own copy
(check_paper_numbers, check_paper_consistency, provenance_breakdown, rq_breakdown):
two places obliged to say the same thing with nothing enforcing it.

ORDER OF STAGES, AND WHY THE SCOPE IS DECIDED ON THE COBOL SIDE
---------------------------------------------------------------
    parse -> COBOL encoding (scope) -> Python emission -> Python encoding -> proof

A program is in scope ("enters the checking path") when its COBOL side yields at
least one Z3-encodable output. That is a property of the input and of the COBOL
encoder, not of our Python generator. The former order (emission before scope) put
every program the generator refused into the checking path, including 334 whose
COBOL side yields nothing encodable: a refusal on an out-of-scope program was being
counted as an in-scope failure.

What stays in the denominator, so that the rate can still fall:
  - a parse that raises, and a COBOL encoding that raises: we cannot tell whether
    the program is in scope, and the failure is ours -> pipeline_failure;
  - an in-scope program our generator refuses, or whose Python we cannot encode or
    solve -> pipeline_failure.
Only "the COBOL side yields no encodable output" leaves the denominator.

States: proved, refuted, partial, pipeline_failure, no_encodable_output.
"""
from __future__ import annotations

import glob
import os
import re
import sys
import time
from collections.abc import Iterator
from typing import Any

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CORPUS = os.path.join(REPO, "benchmark", "cobol_programs")
if REPO not in sys.path:
    sys.path.insert(0, REPO)

from ironproof_core import (
    IronproofParser,
    PythonGen,
    _build_cobol_z3,
    _build_python_z3,
    _domaine_entrees,
    cibles_non_declarees,
    is_expr,
    pic_declares_dans_la_source,
    prove_equivalence,
)

STATES = ("proved", "refuted", "partial", "pipeline_failure", "no_encodable_output")
INDEPENDENT_PREFIXES = {"gnucobol", "dscobol", "nist", "examples", "omp", "omp2"}
COMMUNITY_PREFIXES = {"examples", "omp", "omp2"}


def prefix_of(name: str) -> str:
    return re.sub(r"_[0-9].*", "", name)


def is_independent(name: str) -> bool:
    """Independently authored = not written or generated by us."""
    return prefix_of(name) in INDEPENDENT_PREFIXES


def source_of(name: str) -> str:
    prefix = prefix_of(name)
    if prefix == "gnucobol":
        return "GnuCOBOL"
    if prefix == "gen":
        return "Generated"
    if prefix == "dscobol":
        return "dscobol"
    if prefix == "nist":
        return "NIST"
    if prefix in COMMUNITY_PREFIXES:
        return "Community"
    return "Hand-written"


# Ways data can enter a COBOL program at run time. A program with none of them is
# CLOSED: it has a single execution, and evaluating it on that execution IS its whole
# behaviour. A program with one of them is OPEN even when the encoder models no free
# input -- then a proof covers one point of a program that has many executions.
# Keyword detector on code columns (comment lines skipped), not a parser: it can miss
# an exotic form, and says so here. COPY is excluded: it includes source, not data.
INPUT_SURFACES = (
    ("FILE SECTION", r"\bFILE\s+SECTION\b"),
    ("FD", r"^\s*FD\s"),
    ("SD", r"^\s*SD\s"),
    ("LINKAGE", r"\bLINKAGE\s+SECTION\b"),
    ("READ", r"\bREAD\s"),
    ("PROCEDURE USING", r"\bPROCEDURE\s+DIVISION\s+USING\b"),
    ("SELECT ASSIGN", r"\bSELECT\s.*\bASSIGN\b"),
    ("CALL USING", r"\bCALL\s.*\bUSING\b"),
    ("ACCEPT", r"\bACCEPT\s"),
    ("EXEC SQL", r"\bEXEC\s+SQL\b"),
    ("SORT", r"\bSORT\s"),
)


def input_surfaces(src: str) -> list:
    """Names of the input surfaces present in the program's code columns."""
    code = []
    for raw in src.upper().splitlines():
        if len(raw) > 6 and raw[6] in "*/":
            continue
        code.append(raw[6:72] if len(raw) > 6 else raw)
    text = "\n".join(code)
    return [name for name, pat in INPUT_SURFACES if re.search(pat, text, re.MULTILINE)]


def nonblank_loc(src: str) -> int:
    """Non-empty physical lines: the count under which the paper's benchmark
    statistics are stated."""
    return len([ln for ln in src.splitlines() if ln.strip()])


def classify(name: str, src: str, parser: Any, gen: Any) -> dict[str, Any]:
    """Classify one program. Never raises: every failure becomes a state."""
    rec: dict[str, Any] = {
        "name": name, "source": source_of(name), "independent": is_independent(name),
        "loc": nonblank_loc(src), "state": None, "stage": None,
        "input_surfaces": input_surfaces(src),
        "parse_ok": False, "emit_ok": False, "t": {},
    }
    t0 = time.perf_counter()
    try:
        prog = parser.parse(src)
    except Exception as exc:  # noqa: BLE001 -- every failure is a counted state
        rec["state"], rec["stage"] = "pipeline_failure", "parse:" + type(exc).__name__
        return rec
    rec["parse_ok"] = True
    t1 = time.perf_counter()
    try:
        rep: dict[str, Any] = {}
        inputs, outputs, allvars = _build_cobol_z3(prog, rep)
    except Exception as exc:  # noqa: BLE001
        rec["state"], rec["stage"] = "pipeline_failure", "cobol_encode:" + type(exc).__name__
        return rec
    provable = {k: v for k, v in outputs.items() if is_expr(v)}
    t2 = time.perf_counter()
    if not provable:
        rec["state"] = "no_encodable_output"
        return rec
    try:
        py = gen.generate(prog)
    except Exception as exc:  # noqa: BLE001
        rec["state"], rec["stage"] = "pipeline_failure", "emit:" + type(exc).__name__
        return rec
    rec["emit_ok"] = True
    t3 = time.perf_counter()
    try:
        py_out = _build_python_z3(py, allvars)
        t4 = time.perf_counter()
        proofs = prove_equivalence(
            provable, py_out, inputs, variables=prog.variables,
            source_vars=set(prog.variables),
            unverified=set(rep.get("dropped_outputs", [])),
            cibles_invalides=cibles_non_declarees(prog),
            pic_declares=pic_declares_dans_la_source(src))
        t5 = time.perf_counter()
    except Exception as exc:  # noqa: BLE001
        rec["state"], rec["stage"] = "pipeline_failure", "py_encode_or_solve:" + type(exc).__name__
        return rec
    rec["t"] = {"parse": (t1 - t0) * 1e3, "emit": (t3 - t2) * 1e3,
                "encode": ((t2 - t1) + (t4 - t3)) * 1e3, "check": (t5 - t4) * 1e3}
    # What the quantifier actually ranges over (same function the certificate uses):
    # a proof over a program with no free input, or whose proved outputs depend on
    # none, is an evaluation of constants, not a statement about a translation.
    dom = _domaine_entrees(inputs, provable)
    rec["free_inputs"] = dom.get("free_input_count", 0)
    rec["dep_outputs"] = len(dom.get("proved_outputs_depending_on_a_free_input", []))
    if all(p.proved for p in proofs):
        rec["state"] = "proved"
    elif any(p.status == "REFUTED" for p in proofs):
        rec["state"] = "refuted"
    else:
        rec["state"] = "partial"
    return rec


def iter_corpus(corpus_dir: str | None = None) -> Iterator[dict[str, Any]]:
    parser, gen = IronproofParser(), PythonGen()
    for f in sorted(glob.glob(os.path.join(corpus_dir or CORPUS, "*.cbl"))):
        with open(f) as fh:
            src = fh.read()
        yield classify(os.path.basename(f)[:-4], src, parser, gen)


def counts(records: list) -> dict[str, int]:
    c = {s: sum(1 for r in records if r["state"] == s) for s in STATES}
    c["total"] = len(records)
    c["checking_path"] = c["total"] - c["no_encodable_output"]
    return c
